# Generated by Django 3.1.5 on 2021-01-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCode', models.IntegerField(null=True, unique=True)),
                ('itemName', models.CharField(max_length=200)),
                ('techSpecs', models.TextField()),
                ('make', models.CharField(choices=[('metal', 'metal'), ('plastic', 'plastic'), ('metal & plastic', 'metal & plastic')], max_length=100)),
                ('UOM', models.CharField(max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ('rate',),
            },
        ),
        migrations.CreateModel(
            name='toOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toOrder', to='crud.itemspost')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
    ]
