# Generated by Django 3.1.5 on 2021-01-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='toOrder',
        ),
    ]
