# Generated by Django 3.1.5 on 2021-01-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_delete_toorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='saveOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toOrder', to='crud.itemspost')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
    ]
