# Generated by Django 3.1.5 on 2021-01-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_saveorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveorder',
            name='code',
            field=models.CharField(max_length=200),
        ),
    ]
