# Generated by Django 3.1.5 on 2021-01-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20210125_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveorder',
            name='center',
            field=models.CharField(default='center1', max_length=200),
        ),
    ]
