# Generated by Django 3.1.5 on 2021-01-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_saveorder_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveorder',
            name='itemCode',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='saveorder',
            name='make',
            field=models.CharField(default='number', max_length=100),
        ),
        migrations.AddField(
            model_name='saveorder',
            name='rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='saveorder',
            name='unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemspost',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='saveorder',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
