# Generated by Django 3.1.5 on 2021-01-28 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='requiredOn',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
