# Generated by Django 3.1.5 on 2021-01-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_auto_20210128_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=252)),
                ('requestedBy', models.CharField(max_length=252, null=True)),
                ('q1', models.CharField(max_length=252)),
                ('dN', models.CharField(max_length=252)),
                ('dD', models.DateField()),
            ],
            options={
                'ordering': ('dN', 'dD'),
            },
        ),
    ]
