# Generated by Django 3.1.5 on 2021-01-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
