# Generated by Django 3.1.5 on 2021-01-29 13:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0013_set_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='v1',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
